export const START_FETCHING_PAGE_DATA = 'START_FETCHING_PAGE_DATA';
export const PAGE_DATA_LOADED = 'PAGE_DATA_LOADED';
export const PAGE_DATA_ERROR = 'PAGE_DATA_ERROR';
export const START_FETCHING_SETTINGS_DATA = 'START_FETCHING_SETTINGS_DATA';
export const SETTINGS_DATA_LOADED = 'SETTINGS_DATA_LOADED';
export const SETTINGS_DATA_ERROR = 'SETTINGS_DATA_ERROR'
